name-template: "v{{next_release.version}}"
tag-template: "v{{next_release.version}}"
categories:
  - title: "ðŸš€ Features"
    labels:
      - feat
      - feature
      - type:feature
  - title: "ðŸ› Fixes"
    labels:
      - fix
      - bug
      - type:bug
  - title: "ðŸ§° Maintenance"
    labels:
      - chore
      - refactor
      - ci
      - build
      - type:task
  - title: "ðŸ“ Documentation"
    labels:
      - docs
      - type:documentation
change-template: "* {{pr.title}} (#{{pr.number}})"
change-title-escapes: '\"'
template: |
  ## What's Changed
  {{#categorized}}
  ### {{title}}
  {{#pull_requests}}
  {{#each this}}
  {{> change }}
  {{/each}}
  {{/pull_requests}}
  {{/categorized}}